[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "packaging>=24.2"  # see https://github.com/pypa/twine/issues/1216 for why (and this is not sufficient to overcome the issue)
    # see this issue as well:  https://github.com/pypa/setuptools/issues/4759
]
build-backend = "setuptools.build_meta"

[project]
name="picohttp"
version="0.5.1"
requires-python= ">= 3.7"
authors = [
      { name= "Joe Deuhl", email="joe@thebuehls.com" },
      { name= "Steve Hespelt", email= "shespelt@stevens.edu"},
]
description = "An HTTP 1.0 server framework that is useful for supporting applications where the behavior is constrained and relatively simple"
dependencies = [
   "rutifu"
]
readme = "README.md"
classifiers = [
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
]
# license-files key added in Dec 2024, not recognized by twine validation - why the workarounds (so I can publish this)
# license-files = ["LICENSE"]
#license.file = 'LICENSE'    #  "GPL-3.0-only"

[project.optional-dependencies]
# stuff that can be included via pkg-main[option1]

[project.scripts]
# python script that can get wrapper applied, so script invoked as command

[project.urls]
Repository="https://github.com/jbuehl/picohttp"

[tool.setuptools]
license-files = []  # see https://github.com/pypa/twine/issues/1216, https://github.com/pypa/setuptools/issues/4759 for why
                    # upgrading packaging to the latest (24.2) does not fix the issue

[tool.setuptools.packages.find]
where = ["./"]
include = ["picohttp"]
exclude = ["./tests**"]


[tool.poetry]

[tool.mypy]
mypy_path = 'picohttp/'

[tool.coverage.run]
source =  [
  "picohttp/**"
]
omit = [
  "tests/skip*.py"
]
